version: '2'

x-logging:
  &default-logging
  logging:
    driver: json-file
    options:
      max-size: 100m

services:
  nginx:
    image: jwilder/nginx-proxy:latest
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./srv/nginx/vhost.d:/etc/nginx/vhost.d
      - ./srv/nginx/html:/usr/share/nginx/html
      - ./srv/ssl_certs:/etc/nginx/certs:ro
    ports:
      - "80:80"
      - "443:443"
    <<: *default-logging
    restart: always

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion:v1.13.1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./srv/ssl_certs:/etc/nginx/certs:rw
    volumes_from:
      - nginx
    <<: *default-logging
    restart: always

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      - VIRTUAL_HOST=example.com
      - LETSENCRYPT_HOST=example.com
      - LETSENCRYPT_EMAIL=john.doe@domain.com
      - PGADMIN_DEFAULT_EMAIL=john.doe@domain.com
      - PGADMIN_DEFAULT_PASSWORD=SuperSecret
    privileged: true
    <<: *default-logging
    restart: always
